### ISSUE TITLE
Error when create a azion_edge_application_main_setting

### ISSUE THREAD

**Issue by hebertdougl** [aziontech/terraform-provider-azion#141]
I'm trying to create the resource `azion_edge_application_main_setting` with a `application_acceleration = true`, but I'm getting the following error: 

`When you create a Edge Application: ApplicationAcceleration must be false or remove from request`

In my case this generate a problem which I can't create a rule engine with a bypass cache phase and this the error: 

```
│   68: resource "azion_edge_application_rule_engine" "default" {
│
│ {"behaviors":"Unable to save this rule because to use \"Bypass Cache Phase\" you must first enable
│ Application Accelerator."}
```
Can anyone help me with this? Because I would like to know if it is possible to create a fix in an edge application to create it with an application_acceleration parameter equals to true.

Thanks in advance.

**Comment by cesarmagazord** [comment]
The same thing happens with the l2_caching option:

`
╷
│ Error: L2Caching error 
│ 
│   with module.homeecia.module.my-cdn.azion_edge_application_main_setting.edge_app,
│   on ../modules/edge_d/edge_application.tf line 1, in resource "azion_edge_application_main_setting" "edge_app":
│    1: resource "azion_edge_application_main_setting" "edge_app" {
│ 
│ When you create a Edge Application: L2Caching must be false or remove from request`

So, I think is not possible to create edge application and rule engine with L2 in one run.

**Comment by maxwelbm** [comment]
@hebertdougl  @cesarmagazord  Currently, in API v3, no module is activated on creation, so if it is not possible to create our document with additional fields https://registry.terraform.io/providers/aziontech/azion/latest/docs/resources/edge_application_main_setting, we will have to correct this situation.

But one solution is to create the application from scratch and update the modules
